title: "Mon site Jekyll"
description: "Un site de test pour GitHub Pages"
baseurl: "" # Change cela si tu déploies sur un sous-répertoire
url: "https://github.com/Dixchiffres/ubsbanquech.git" # Remplace <USERNAME> par ton nom d'utilisateur GitHub
theme: jekyll-theme-primer
